#remote_theme: pages-themes/hacker@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

theme: minima
header_pages:
  - about.md
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/Ahmed-AG" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/ahmadabugharbieh/" }
